#include <furi.h>
#include <furi_hal.h>
#include <gui/gui.h>
#include <gui/icon_i.h>
#include "magic_beacon.h"
#include "scenes/scene_template_menu.h"
#include "scenes/scene_main_menu.h"
#include "scenes/scene_file_file_browser.h"
#include "scenes/scene_file_menu.h"
#include "scenes/scene_input_payload.h"
#include "scenes/scene_input_address.h"
#include "scenes/scene_display_text.h"
#define TAG "magic_beacon"

/* generated by fbt from .png files in images folder */
#include <magic_beacon_icons.h>

/** collection of all scene on_enter handlers - in the same order as their enum */
void (*const magic_beacon_scene_on_enter_handlers[])(void*) = {
    magic_beacon_scene_main_menu_on_enter,
    magic_beacon_scene_template_menu_on_enter,
    magic_beacon_scene_file_file_browser_on_enter,
    magic_beacon_scene_file_menu_on_enter,
    magic_beacon_scene_input_payload_on_enter,
    magic_beacon_scene_input_address_on_enter,
    magic_beacon_scene_display_text_on_enter};

/** collection of all scene on event handlers - in the same order as their enum */
bool (*const magic_beacon_scene_on_event_handlers[])(void*, SceneManagerEvent) = {
    magic_beacon_scene_main_menu_on_event,
    magic_beacon_scene_template_menu_on_event,
    magic_beacon_scene_file_file_browser_on_event,
    magic_beacon_scene_file_menu_on_event,
    magic_beacon_scene_input_payload_on_event,
    magic_beacon_scene_input_address_on_event,
    magic_beacon_scene_display_text_on_event};

/** collection of all scene on exit handlers - in the same order as their enum */
void (*const magic_beacon_scene_on_exit_handlers[])(void*) = {
    magic_beacon_scene_main_menu_on_exit,
    magic_beacon_scene_template_menu_on_exit,
    magic_beacon_scene_file_file_browser_on_exit,
    magic_beacon_scene_file_menu_on_exit,
    magic_beacon_scene_input_payload_on_exit,
    magic_beacon_scene_input_address_on_exit,
    magic_beacon_scene_display_text_on_exit};

/** collection of all on_enter, on_event, on_exit handlers */
const SceneManagerHandlers magic_beacon_scene_event_handlers = {
    .on_enter_handlers = magic_beacon_scene_on_enter_handlers,
    .on_event_handlers = magic_beacon_scene_on_event_handlers,
    .on_exit_handlers = magic_beacon_scene_on_exit_handlers,
    .scene_num = APP_SCENE_COUNT};

/** custom event handler - passes the event to the scene manager */
bool magic_beacon_scene_manager_custom_event_callback(void* context, uint32_t custom_event) {
    FURI_LOG_T(TAG, "magic_beacon_scene_manager_custom_event_callback");
    furi_assert(context);
    MagicBeaconApp* app = context;
    return scene_manager_handle_custom_event(app->scene_manager, custom_event);
}

/** navigation event handler - passes the event to the scene manager */
bool magic_beacon_scene_manager_navigation_event_callback(void* context) {
    FURI_LOG_T(TAG, "magic_beacon_scene_manager_navigation_event_callback");
    furi_assert(context);
    MagicBeaconApp* app = context;

    return scene_manager_handle_back_event(app->scene_manager);
}

/** initialise the scene manager with all handlers */
void magic_beacon_scene_manager_init(MagicBeaconApp* app) {
    FURI_LOG_T(TAG, "magic_beacon_scene_manager_init");
    app->scene_manager = scene_manager_alloc(&magic_beacon_scene_event_handlers, app);
}

/** initialise the views, and initialise the view dispatcher with all views */
void magic_beacon_view_dispatcher_init(MagicBeaconApp* app) {
    FURI_LOG_T(TAG, "magic_beacon_view_dispatcher_init");
    app->view_dispatcher = view_dispatcher_alloc();

    // allocate each view
    app->list = variable_item_list_alloc();
    app->byte_input = byte_input_alloc();

    app->file_path = furi_string_alloc();
    app->file_browser = file_browser_alloc(app->file_path);

    app->text_box = text_box_alloc();

    app->submenu = submenu_alloc();

    // assign callback that pass events from views to the scene manager
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);

    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, magic_beacon_scene_manager_custom_event_callback);

    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, magic_beacon_scene_manager_navigation_event_callback);

    view_dispatcher_add_view(
        app->view_dispatcher, APP_VIEW_LIST, variable_item_list_get_view(app->list));

    view_dispatcher_add_view(
        app->view_dispatcher, APP_VIEW_BYTE_INPUT, byte_input_get_view(app->byte_input));

    view_dispatcher_add_view(
        app->view_dispatcher, APP_VIEW_FILE_BROWSER, file_browser_get_view(app->file_browser));

    view_dispatcher_add_view(
        app->view_dispatcher, APP_VIEW_TEXT_BOX, text_box_get_view(app->text_box));

    view_dispatcher_add_view(
        app->view_dispatcher, APP_VIEW_SUBMENU, submenu_get_view(app->submenu));
}

/** initialise app data, scene manager, and view dispatcher */
MagicBeaconApp* magic_beacon_init() {
    FURI_LOG_T(TAG, "magic_beacon_init");
    MagicBeaconApp* app = malloc(sizeof(MagicBeaconApp));
    magic_beacon_scene_manager_init(app);
    magic_beacon_view_dispatcher_init(app);
    return app;
}

/** free all app data, scene manager, and view dispatcher */
void magic_beacon_free(MagicBeaconApp* app) {
    FURI_LOG_T(TAG, "magic_beacon_free");

    ble_stop_advertising();

    view_dispatcher_remove_view(app->view_dispatcher, APP_VIEW_LIST);
    view_dispatcher_remove_view(app->view_dispatcher, APP_VIEW_BYTE_INPUT);
    view_dispatcher_remove_view(app->view_dispatcher, APP_VIEW_FILE_BROWSER);
    view_dispatcher_remove_view(app->view_dispatcher, APP_VIEW_TEXT_BOX);
    view_dispatcher_remove_view(app->view_dispatcher, APP_VIEW_SUBMENU);

    variable_item_list_free(app->list);
    byte_input_free(app->byte_input);
    file_browser_free(app->file_browser);
    text_box_free(app->text_box);

    view_dispatcher_free(app->view_dispatcher);

    scene_manager_free(app->scene_manager);

    furi_string_free(app->file_path);

    submenu_free(app->submenu);

    free(app);
}

/** go to trace log level in the dev environment */
void magic_beacon_set_log_level() {
#ifdef FURI_DEBUG
    furi_log_set_level(FuriLogLevelTrace);
#else
    furi_log_set_level(FuriLogLevelError);
#endif
}

/** entrypoint */
int32_t magic_beacon_app(void* p) {
    UNUSED(p);
    magic_beacon_set_log_level();

    // create the app context struct, scene manager, and view dispatcher
    FURI_LOG_I(TAG, "starting...");
    MagicBeaconApp* app = magic_beacon_init();

    // set the scene and launch the main loop
    Gui* gui = furi_record_open(RECORD_GUI);
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    scene_manager_next_scene(app->scene_manager, APP_SCENE_MAIN_MENU);
    FURI_LOG_D(TAG, "Starting dispatcher...");
    view_dispatcher_run(app->view_dispatcher);

    // free all memory
    FURI_LOG_I(TAG, "finishing...");
    furi_record_close(RECORD_GUI);
    magic_beacon_free(app);
    return 0;
}
